export { default as external } from "../assets/external.svg"
export { default as code } from "../assets/code.svg"
export { default as gmail } from "../assets/gmail.svg"
export { default as linkedin } from "../assets/linkedin.svg"
export { default as discord } from "../assets/discord.svg"
export { default as about } from "../assets/about.png"
export { default as contact } from "../assets/contact.png"
export { default as more } from "../assets/more.svg"
export { default as githublogo} from "../assets/githubhome.svg"
export {default as JobSpot} from "../assets/projects/JobSpot.png"
export { default as tailwind } from "../assets/tailwind.png"
export { default as user } from "../assets/user.png"
export { default as projects } from "../assets/projects.png"
export { default as tech } from "../assets/tech.png"
export { default as contact_icon } from "../assets/contact-sidebar.png"